CREATE TABLE WORKSHOPS(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    TYPE VARCHAR(25) NOT NULL,
    NAME VARCHAR(25) NOT NULL,
    CONTENT TEXT,
    PRIMARY KEY(ID)
) ENGINE=MYISAM COLLATE LATIN1_GENERAL_CS;
